### ISSUE TITLE
Pre-configuring signalk server

### ISSUE THREAD

**Issue by wmbutler** [SignalK/signalk-server#1251]
I'm attempting to build a signalk server that's pre-configured with certain plugins activated and configured. My goal is to be able to do this from the baseline signalk server install. I thought I could just place the necessary json config files as shown:

package.json
```
{
  "name": "signalk-server-config",
  "version": "0.0.1",
  "description": "This file is here to track your plugin and webapp installs.",
  "repository": {},
  "license": "Apache-2.0",
  "dependencies": {
    "signalk-to-influxdb": "^1.8.0"
  }
}
```

signalk-to-influxdb.json
```
{
  "configuration": {
    "protocol": "http",
    "host": "localhost",
    "port": 8086,
    "database": "boatdata",
    "batchWriteInterval": 0,
    "resolution": 200,
    "recordTrack": false,
    "separateLatLon": false,
    "overrideTimeWithNow": false,
    "storeOthers": false,
    "blackOrWhite": "Black"
  },
  "enabled": true
}
```

Dockerfile
```
COPY package.json /root/.signalk/package.json
COPY signalk-to-influxdb.json /root/.signalk/plugin-config-data/signalk-to-influxdb.json
```

What I found is that the files are in fact copied to the right place, but since I'm installing a brand new instance of signalk, it doesn't appear that the plugins have been initialized. There's no `node_modules` directory, so I'm still required to go to the frontend to enable the plugin, etc. Is there a way to script this to trigger the building of the node_modules dir?

Alternatively, is there a better way for me to approach this? I also thought about providing a backup file that could be restored, but my goal is to have a docker container that will make it really easy for people to start experimenting with things by making sure that signalk, influx and grafana are working right out of the box.

Here's a link to the [repo](https://github.com/wmbutler/signalk-influx-grafana-docker)

**Comment by tkurki** [comment]
The solution to your particular problem is running `npm install` in the .signalk directory to install the plugins listed in the package.json there.

Installing sk server from git needs a build step to transpile TypeScript to JavaScript. Why not [install from npm](https://github.com/SignalK/signalk-server/blob/master/Dockerfile#L15-L16)? 

I suppose that _one image to rule them all_ method is one way to do this. Another would be to use [Docker Compose]( https://github.com/tkurki/marinepi-provisioning/blob/master/roles/signalk-docker/templates/) to set up the different containers. The repo I linked also provides an example of an autoprovisioned Grafana datasource, that is something that you might want to look into. This is what I use today, or to be precise used last season and plan to use this coming season. Individual containers also allows pulling new versions for individual images instead of one image for any change.

Is this for experimentation or for actually using the image "in production"? If for real use you need to figure out (serial) device and can network device access.

Furthermore I can't claim extensive Docker experience, but a common approach seems to be to use bind or mounts for configuration and data files. For example if somebody installs an extra SK server plugin how does the end user keep changes in package.json and the plugin's configuration data? Their connection configuration a k a settings.json? Same thing for Influx data files. What about plugin updates?

**Comment by tkurki** [comment]
Closing, reopen if there's more to it.
