### ISSUE TITLE
Timestamp management

### ISSUE THREAD

**Issue by sergei** [SignalK/signalk-server#1302]
Some plugins do produce and post deltas using current system time. It's probably not a good idea. 
- It's definitely wong wrong during the log file replay.
- It can be wrong if the system time is not set correctly 

Probably better approach would be for the server to timestamp all deltas based on the elapsed time since trusted timestamp was received. Since there are some plugins that change the system time the elapsed time should come from monotonic clock to avoid the jump in the timestamp value.

The implication of that change probably would be the concept of unknown time, i.e. time before the trusted timestamps was posted.

Indeed there are very few sources that can be trusted to carry the proper time, e.g. $GPRMC and only in the case if the position is valid. If position is not valid some GPS manufacturers still output non null UTC time field that can be completely bogus.

**Comment by tkurki** [comment]
Hmm. Redoing the whole time management on the server is one thing. 

Fixing things so that log playback has usable timestamps is another. 

Afaik plugins do not produce timestamped deltas and if they do they should be changed not to do so. Server adds timestamps to deltas without one. Then we can add a way to instruct the server to use the last timestamp it has seen that originated from data coming from outside the server. This should fix the logfile playback issue.

**Comment by tkurki** [comment]
I don't think your idea about a monotonic clock fixing the problem with something altering the system time helps. 

A sample scenario:
- server starts and gets starting time off a (hypothetical) monotonic clock and the system time at startup
- server proceeds to timestamp things with `system_time_at_startup + current_monotonic_clock - monotonic_clock_at_startup`
- something resets system time to another value
- what do we do now?

Presumably there is a reason for resetting the system time  and its original value was wrong. Monotonic clock value does not help, because we need to come up with absolute timestamps and the jump is unavoidable.

**Comment by sergei** [comment]
Unfortunately the plugins do produce the timestamped delta. That's how I've noticed that issue. The example would be 
[signalk-derived-data](https://github.com/SignalK/signalk-derived-data/blob/master/index.js) 
```
let delta = {
                  context: 'vessels.' + app.selfId,
                  updates: [
                    {
                      timestamp: new Date().toISOString(),
                      values: values
                    }
                  ]
                }

                // app.debug("got delta: " + JSON.stringify(delta))
                app.handleMessage(plugin.id, delta)
```
Another plugin is signalk-polar:
```
const data = {
    context: "vessels." + app.selfId,
    updates: [
      {
        source: {
          type: "server",
          sentence: "none",
          label: "calculated",
          talker: "signalk-polar"
        },
        timestamp: utilSK.timestamp(),
        values: [
          {
            path: key,
            value: value
          }
        ]
      }
    ]
  }
```
The latter is compounded with the [bug](https://github.com/SignalK/nmea0183-utilities/issues/17) in utilSK.timestamp() produces the data which is month off.

**Comment by sergei** [comment]
My fix proposal was *never* to use the platform time and only use the time provided by the GPS. 

Not sure how realistic it is since it would make the GPS input mandatory. Maybe to alleviate that there can be a plugin that would populate navigation.datetime from the system time on the systems where system time can be trusted.

**Comment by tkurki** [comment]
> only use the time provided by the GPS

I don't think that is a practical mechanism. It does not provide continuous time information and like you said makes GPS obligatory. 

I fail to see how it would be better than setting system time from GPS time and using it for timestamping.

**Comment by tkurki** [comment]
>the plugins do produce the timestamped delta

Oh. I think we should fix the plugins to produce deltas without timestamps. Can you help with that?

**Comment by sergei** [comment]
Yes, I can do the PRs for signalk-derived-data and signalk-polar

**Comment by sergei** [comment]
The @signalk/nmea0183-signalk is also using the current time if the tag is not specified:
```
> const Parser = require('@signalk/nmea0183-signalk')
> const parser = new Parser()
> parser.parse('\\s:airmar dst800,c:1438489697*13\\$SDDBT,17.0,f,5.1,M,2.8,F*3E')
{ updates:
   [ { source: [Object],
       timestamp: '2015-08-02T04:28:17.000Z',
       values: [Array] } ] }
> d = parser.parse('$SDDBT,17.0,f,5.1,M,2.8,F*3E')
{ updates:
   [ { source: [Object],
       timestamp: '2021-04-09T15:54:15.081Z',
       values: [Array] } ] }
> 
```

**Comment by tkurki** [comment]
I think this issue has been fixed to the extent it can be fixed.
