### ISSUE TITLE
raspberry pi install: node-js version and other depreciated packages

### ISSUE THREAD

**Issue by mestafin** [SignalK/signalk-server#1372]
I installed SignalK on a raspberry pi and received a lot of warnings, and notifications of depreciated packages and vulnerabilities.

node-js version 10 is still required, which is EOL as everyone knows by now.

Is there a timeline to address and fix these issues?

**Comment by tkurki** [comment]
There's 1.41.0-beta.3 per eb874e3ccc4eb8efa55e44b92c13165210d9ddbb with official update to using Node 16 out with no known problems, so a question of days rather than weeks. See also 

Depreciated packages and vulnerabilites are an ongoing struggle.

See also https://github.com/SignalK/signalk-server/wiki/Updating-to-Node.js-16
