### ISSUE TITLE
Logout response is not JSON

### ISSUE THREAD

**Issue by godind** [SignalK/signalk-server#1480]
Minor bug: logout API call `/signalk/v1/auth/logout` returns a body of Content-Type `text/html` with content `Logout Ok`. All is fine with the API call  but for the body string format that does not match the requested header Content-Type of `application/json`.

Modern Browsers block the response with an error:

> - error: SyntaxError: Unexpected token 'L', "Logout OK" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at XMLHttpRequest.onLoad...
> - text: 'Logout OK'

Everything else is fine with the response: `status=200`, etc.

Thanks!

**Comment by tkurki** [comment]
See #1478

**Comment by godind** [comment]
@tkurki Hi. following the PRs I don't think this was fixed. Maybe my error...

The problem is in the logout body response. The call completes fine (200) but the browser complains about the content is the body not being valid json. Simple fix

**Comment by tkurki** [comment]
I don’t think we have specufies anywhere the content type for the logout response or what the response should contain, so strictly speaking this is not a bug. If you call the api so that you do not process the response at all you should be able to work around the issue.

But I think it makes sense to return json here, I’ll see about changing that.
