### ISSUE TITLE
Feature: change default config value "Allowed CORS Origin"

### ISSUE THREAD

**Issue by godind** [SignalK/signalk-server#1481]
I think I found another minor bug: logout API call returns a body with Logout Ok. All is fine but for the body string format that does not match the header content type of JSON as it’s returns a plain string.

Browser blocks the response with something like: ERROR: unexpected format. Body content is not a valide JSON object. Everything else is fine with the response: status=200, etc.

NOTE: using a Chrome CORS Plugin I have the ability to play with CORS rules and disable it completely so I can continue my work until the fix. Just wanted to share so you know there are browser dev plug-ins to play with CORS

**Comment by tkurki** [comment]
the spec does not specify a response for logout. the response is now text/html, which is kinda stupid for an API call

**Comment by tkurki** [comment]
The title of this issue is totally misleading and the content type of the `/signalk/v1/auth/logout` response is `text/html` not JSON. Reopen and retitle if you feel there's something specific to fix here.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/1049678/194740600-4b2332c5-11c6-40b8-af5f-3e6b5ebb3da7.png">

**Comment by godind** [comment]
Reopened as #1483
