### ISSUE TITLE
Friendly/human readable/localized field on data

### ISSUE THREAD

**Issue by AndreasSchutz** [SignalK/signalk-server#1488]
Is it possible to add a name field in data path? Ex. "electrical.batteries.1.voltage" could have a human readable field that contains "Motor battery" or something localized like "Motorbatteriets spänning". To be used for identification of data and in applications like InstrumentPanel.

**Comment by sbender9** [comment]
You can use the path-mapper plugin. And if your client supports it, "displayName" meta data.

**Comment by tkurki** [comment]
This issue is a bit confusing, as we have already some mechanisms for making the data more human understandable:
- paths with device id as a path element can be mapped to more understandable ones: for example use `path-mapper` to map incoming n2k data (that use n2k device id) `electrical.batteries.1.voltage` => `electrical.batteries.house.voltage`
- [using metadata to add a displayName](https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data) to a path and UIs like InstrumentPanel will use that instead of the path

One thing that we can't do now is having separate `displayName`s for a single path but different sources:
>For example, both my depth sounder and speed log report  water temperature. I can figure out which is which because of which hs the speed and which has depth, but it would be nice if I could alias n2k-on-ve.can-socket.2.0 to “depthsounder”

Localisation support is a separate issue.

**Comment by tkurki** [comment]
Added https://github.com/SignalK/specification/issues/646
