### ISSUE TITLE
Source ID format keeps changing

### ISSUE THREAD

**Issue by tingles2233** [SignalK/signalk-server#1492]
I have a weird one that showed up in the past 1-2 updates. Currently running 1.45.0.

My source ID keeps changing formats and seems to be at random.. it has now happened 3-4 times over the past few weeks. I thought it was related to upgrading to 1.45.0 so I updated the format to the short format "nema2000.31" for example. (Albeit I could not find anything in the change logs on this)

Then this morning I see that it changed back to the long format "nema2000.c03c8d007abfe40f".

I grabbed a screenshot of SignalK data browser as you can see each entry is doubled up with the short and long, you can also see the timestamp on the short format is now older than the new one. If I reboot/restart the server the browser resets and only shows only the long format. 

Anyone know what is going on here is it user error or a bug?
![image](https://user-images.githubusercontent.com/58663637/198843205-268a1f1e-5a9a-4af4-b3dd-8523ddb22818.png)

**Comment by tkurki** [comment]
The "short format" uses addresses that are negotiated on the fly, which is why we added the `Use CAN Name` option or "long names".

I have no idea why your persisted setting would be switching from N2K ids to CAN names. Are you sure you rebooted after the change?

The logic related to CAN names only works so that the n2k integration code keeps track of address claims on the N2k bus so that it has an `id - CAN Name` table that it uses to populate the canName field. If this logic has for some reason missed the address claims it does not have CAN names for some or all the sources and falls back to using ids. Then when later on there are more address claims it picks up the then current `id - CAN Name` mappings and starts to use the newly found CAN Name. This explains the screenshot: the id sourced data is older than CAN name sourced data.

The server does request metadata (including CAN Name) for all the sources, but if it fails to get it it will proceed to handle data without it, using the id. In this case you should be seeing messages like _n2k-signalk: unable to detect can name for src ..._ in your server's log after startup.

**Comment by tkurki** [comment]
Closing as inactive.
