### ISSUE TITLE
Plugin configuration API not reporting correct 'enabledByDefault' property

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1605]
I have a plugin 'metadata' which is enabled by default in package.json with:
```
"signalk-plugin-enabled-by-default": true
```
However, if browse to:  ```http://localhost:3000/plugins/metadata/``` I get:
```
{
  "enabled":true,
  "enabledByDefault":false,
  "id":"metadata",
  "name":"pdjr-skplugin-metadata",
  "version":"1.1.0"
}
```

**Comment by tkurki** [comment]
`enabledByDefault` in that response means "is the plugin enabled because it has signalk-plugin-enabled-by-default in package.json even if there is no configuration for it".

If you remove your plugin's configuration file and restart you should see 

```
  "enabled":true,
  "enabledByDefault":true,
```
- the plugin is enabled
- it is enabled because of the signalk-plugin-enabled-by-default in package.json, not because the user has enabled it via configuration

https://github.com/SignalK/signalk-server/blob/master/src/interfaces/plugins.ts#L654-L659

**Comment by preeve9534** [comment]
Thanks for clarifying the semantics here @tkurki. Closing this. P
