### ISSUE TITLE
Upgrade react-jsonschema-form

### ISSUE THREAD

**Issue by JacoKoster** [SignalK/signalk-server#1613]
Currently SignalK is using https://github.com/peterkelly/react-jsonschema-form-bs4 for forms. This has been Deprecated for about 2 years. 

Recommended to upgrade to https://github.com/rjsf-team/react-jsonschema-form instead.

**Comment by tkurki** [comment]
Is there a more concrete reason for upgrading than it being deprecated? I mean there are several other components that have fallen behind, like React 16, but I don't think we should have issues for each of them.

Just to be clear: I am not opposed to upgrading the form thing, just thinking that there's so much to improve with the plugin configuration mechanism that the driver is or should be improvement for the user.

@KEGustafsson you looked into this previously if I recall correctly?

**Comment by KEGustafsson** [comment]
Update is doable but need quite much work. Tested with the your proposal form and as it is look&feel will change, so customization to get it looking same ss now was the issue.

I ended to make a fork from bs4 and updated that.
https://github.com/KEGustafsson/react-jsonschema-form-bs4
but we agreed earlier that we won't take this into use.

Most of the installation time warning are coming from this package and that was the original reason to update it. Personally I have used this upgraded bs4 package since I made and it is working fine

**Comment by JacoKoster** [comment]
> Is there a more concrete reason for upgrading than it being deprecated? I mean there are several other components that have fallen behind, like React 16, but I don't think we should have issues for each of them.
> 
> Just to be clear: I am not opposed to upgrading the form thing, just thinking that there's so much to improve with the plugin configuration mechanism that the driver is or should be improvement for the user.
> 
> @KEGustafsson you looked into this previously if I recall correctly?

I agree, I'll close this one :)
