### ISSUE TITLE
Disabling linked plugins on update

### ISSUE THREAD

**Issue by VladimirKalachikhin** [SignalK/signalk-server#1743]
SignalK 2.8.1
After installing any updates, the plugins, linked as [described](https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin.md#link-your-project-to-signal-k-server), disappear from the SignalK server. It needs to be linked again.

**Comment by tkurki** [comment]
Added a note about it in the doc.

I think this is [expected behavior of npm](https://github.com/npm/cli/issues/2380), even if it does not make sense in our context. Have been bitten by this, several times, but I still don't think it is worth spending effort on.

Unless somebody can prove me wrong and has a nice fix for it...

**Comment by VladimirKalachikhin** [comment]
Well, I didn't know...
I'll have to write a bash.
