### ISSUE TITLE
No more the "/static/" directory?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [SignalK/signalk-server#1748]
Signal K Server version 2.8.2
The e-inkDashboard plugin has stopped working
```
GET
http://192.168.1.70:3531/static/dashboard.css
[HTTP/1.1 500 Internal Server Error 0ms]
```
... and other from `/static/` directory.

**Comment by tkurki** [comment]
That has never worked.

**Comment by VladimirKalachikhin** [comment]
Ha! It's worked before 2.8.2
I say's: "e-inkDashboard plugin". [The bug with zones](https://discord.com/channels/1170433917761892493/1240726737273487502/1242932235838165002) was found with this plugin. The plugin worked with 2.8.1 The plugin has always used the `/static/` directory, since 2021.

**Comment by tkurki** [comment]
SignalK Server's http server has never handled requests to `/static/`, so requests to that path have never worked. How could it even work for multiple plugins, if multiple plugins tried to use content from under a non-plugin specific path?

Apparently your plugin [creates its own http server with default port 3531 as in the picture](https://github.com/VladimirKalachikhin/e-inkDashboard/blob/master/index.js#L1237), so the problem is with your own code.

Creating your own http server is pretty stupid: it will not work at all in docker or behind a reverse proxy and your [attempt to find out the server's external address](https://github.com/VladimirKalachikhin/e-inkDashboard/blob/master/index.js#L92) only works in certain operating system.

Instead you could read the server's plugin documentation and find the [documented way to create http endpoints](https://demo.signalk.io/documentation/develop/plugins/server_plugin_api.html?highlight=registerwith#exposing-custom-http-paths--openapi) and you could simply use relative or absolute-but-plugin-specific urls in your html.

I recently created a plugin/webapp that [redirects from the static webapp html](https://github.com/tkurki/ejs-plugin/blob/main/public/index.html#L7) to the plugin's [page with registerWithRouter handler](https://github.com/tkurki/ejs-plugin/blob/main/index.js#L46-L63).

**Comment by VladimirKalachikhin** [comment]
Thank you, Teppo, for reminding me how my plugin works.
Even if you don't like the way it's made, I had my reasons for making it that way. Time has confirmed the correctness of my solutions.
However, you were correct in stating that "so the problem is with your own code": in the JavaScript, not every correct code is always correct. Stricter coding restored functionality, and I'm no longer interested in what changed in version 2.8.2 that previously working code stopped working.
