### ISSUE TITLE
Connect/subscribe without getting cached data

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#953]
AS reported by @Hakansv: when OpenCPN connects to the SK server it gets always a burst of latest values for both self and AIS targets. Some of this data may be stale and may cause initil confusion, before most (but not all) data will be replaced with fresh data.

I think it makes sense to add a way to connect/subscribe without getting cached data.

With ws we have url and query string at our disposal, so adding an extra parameter to allow suppressing the cached data.

For TCP streaming there is no query string, so I don't see any other than adding something to the `subscribe` message.

**Comment by tkurki** [comment]
What should the parameters be named? I am drawing a blank right now...

**Comment by Hakansv** [comment]
Without insight in the program structure just a name proposal idea to push forward.
Now:
"{\"context\":\"vessels.self\",\"subscribe\":[{\"path\":\"navigation.*\"}]}\r\n";
Suggestion:
"{\"context\":\"vessels.self\",\"subscribe, nocash\":[{\"path\":\"navigation.*\"}]}\r\n";

**Comment by tkurki** [comment]
When using JSON one should use explicit fields and not encode stuff into a string.

Maybe
```
{
  "context": "vessels.self",
  "noCached": true,
  "subscribe": [
    {
      "path": "navigation."
    }
  ]
}
```
or
```
{
  "context": "vessels.self",
  "subscribe": [
    {
      "path": "navigation.",
      "noCached": true
    }
  ]
}
```

I think I prefer the first one - you can always issue separate subscribe messages if you want this to behave differently for different paths, but I assume the most common case would be "top level", eg. it is about all paths in a subcription message.

**Comment by Hakansv** [comment]
I've no aspects at all about JSON programming. You're the expert.
We'll of course adept to the logic used to set appropriate parameters. What we would like is a general context to avoid any cached data. Now outdated vessel, AtoN and Aircraft data are received at every SK connection.
So how would or connection parameters look like with your example?

**Comment by sbender9** [comment]
I’m not sure this is the right solution. This is done because some data might not be updated regularly. For example, I have a fridge monitor that only updates ever couple of minutes and would prefer not to have to wait 2 minutes to see the latest data. 

There is a setting under Server -> Settings “ Maximum age of inactive vessels' data” which defaults to five minutes. Maybe we should make the default smaller?

**Comment by tkurki** [comment]
If there is an **option** to say `noCached` your use case would work just like it does today. Am I not seeing something?

**Comment by Hakansv** [comment]
Ahaa.. That may be a (simple) solution as well.
Looking to my server it's set to 60 minutes and is what I remember never touched. Could it be default to 60 instead of intended 6?
I'll make test to set it to 6 minutes and check the result. 6 minutes would be reasonable time, not less since OCPN use that time as a default "lost target" indication. The figure is based on some AIS transponder for certain vessels use up to 6 minutes transmit delays.
I'll be back.

![bild](https://user-images.githubusercontent.com/7202854/74589849-53424080-5009-11ea-929a-07079e7cf3a8.png)

**Comment by sbender9** [comment]
Oops. You’re right, I looked at my setting and assumed it was the default. I’m ok with changing the default to 6 minutes.

**Comment by Hakansv** [comment]
I've tested the OCPN effects of different "Maximum age of inactive vessels" and it's not convincing so far.
Six minutes was to long as well. When I connect I get a number of positioned targets and on a live AIS update the target moves instantly and gets a SOG sometimes double the actual speed. 
I also tried 0.0 as maximum age but that's not accepted (back to default) and then 0.1.
But even 0.01 minutes gave a similar false SOG. 
For OCPN we don't need any cached data but if we can cope with it in any other way than a "nocache" I don't know.
Could @bdbcat have anything to add here?

![bild](https://user-images.githubusercontent.com/7202854/74591492-d9b24e80-5018-11ea-8cf8-ef92721ed207.png)

**Comment by bdbcat** [comment]
Will someone post here a sample of the exact JSON stream containing cached data initially seen by a new client connection?   And method to reproduce?

Thanks
Dave

**Comment by Hakansv** [comment]
Dave..
What I did now was to log here:  (Attached)
OnEvtOCPN_SignalK(OCPN_SignalKEvent &event................
auto root = event.GetValue(); 
The first AIS vessels has a time stamp about 20-30 seconds old.  But if I'm correct we don't know when the actual data was received to SK. It's probably "last known data"? If the time stamp had printed receive time there would have been more time differences between different vessels?

I don't understand the exact impact of the server setting: "Minimum age of inactive vessels data" Now set to 0.01 minutes. But since received data time stamp is 20 seconds this, 0.6 sec, may not influence.

I've also tried different subscription "policy=[instant|ideal|fixed]. Default: ideal" but without any impact on this.

We've to solve this in some way. Outdated or "last known" data received at connect can cause serious misunderstandings. Especially a foggy night. OCPN does not need "last known data" (time) manipulated by SK. We only need date received to SK after a OCPN connect. 

[First_received_SD_data.log](https://github.com/SignalK/signalk-server-node/files/4209632/First_received_SD_data.log)

**Comment by bdbcat** [comment]
Hakan...
How about a simple solution:
We arrange to discard any sK data that has a timestamp older than the actual time at the moment of connection.
Would this work?
Dave

**Comment by tkurki** [comment]
The `hello` message that the client gets upon connection has the SK server's timestamp. Any deltas older than that is by definition "old".

But I think being able to connect without getting cached data has use beyond OpenCPN integration. Also it would remove the burden from the SK client to deal with timestamps.

So what do you think if we 
- add support for a `serveCached` boolean valued url query parameter, that changes the default cache related behavior for that connection. If missing the behavior is up to the server.
- add a root property with the same name `serveCached` to the subscribe message that changes the cache behavior for that subscription

**Comment by tkurki** [comment]
Also: I changed from `noCached` further above to `serveCached` because I think a property should not be negated unless there are very clear reasons to do so.

**Comment by bdbcat** [comment]
Teppo...

This looks good to me, and seems logically sound.
I wonder about implementation timeline, though.  There are at least some  existing sK servers in the field (e.g. OpenPlotter).  How, and how often, can we expect them to be updated?

**Comment by tkurki** [comment]
SK servers have autoupdate if installed on Linux like in OpenPlotter: there is a message in the admin UI for a server update being available and update operation is one push of a button plus restart. Naturally there needs to a internet connectivity and the user must open the admin UI.

I looked into the implementation and it looked pretty straightforward.

**Comment by Hakansv** [comment]
@tkurki 
Very good! Look forward to that elegant solution.
Dave, we do need the O user to make a server update i any case. AIS class and others are essential as well. I'll look into SART stuff. It may be also this need some small adjustments.
The server version can be checked and message the user for an update if needed. Also, as Teppo says, is the SK message about an available update clear enough and nicely equipped with link to accomplish.

**Comment by sailoog** [comment]
SK server is managed by a Debian package in OpenPlotter. Every time this package is updated the SK server is also updated.

**Comment by tkurki** [comment]
@sailoog is the server's own update mechanism disabled?

**Comment by sailoog** [comment]
No no, just an add on

**Comment by sbender9** [comment]
> @tkurki
> Very good! Look forward to that elegant solution.
> Dave, we do need the O user to make a server update i any case. AIS class and others are essential as well. I'll look into SART stuff. It may be also this need some small adjustments.
> The server version can be checked and message the user for an update if needed. Also, as Teppo says, is the SK message about an available update clear enough and nicely equipped with link to accomplish.

There is also a notification that tells the user that there is an update available.  Have you looked into adding support for notifications?

**Comment by tkurki** [comment]
We eventually settled on `sendCached` url parameter, as documented at https://signalk.org/specification/1.7.0/doc/streaming_api.html?highlight=cached#websocket-api-signalkversionstream
